/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pedroabarcaiiproyecto.gui;

import java.awt.*;
import javax.swing.*;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import pedroabarcaiiproyecto.bo.CuadroBO;
import pedroabarcaiiproyecto.entidades.Cuadro;

/**
 *
 * @author Pedro
 */
public class FrmTablero extends javax.swing.JFrame {

        int x;
        int y;
        CuadroBO cuadroBO;
        
    public FrmTablero() {
        initComponents();
        x = 4;
        y = 4;
        cuadroBO = new CuadroBO();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plnTablero = new javax.swing.JPanel();
        pnlCrucigrama = new javax.swing.JPanel();
        pnlPistas = new javax.swing.JPanel();
        txtPista = new javax.swing.JTextArea();
        btnGenerar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plnTablero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(plnTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlCrucigrama.setBackground(new java.awt.Color(255, 255, 255));
        pnlCrucigrama.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 255)));
        pnlCrucigrama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pnlCrucigrama, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 400, 350));

        pnlPistas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 255)));
        pnlPistas.setForeground(new java.awt.Color(255, 255, 255));
        pnlPistas.setLayout(new java.awt.BorderLayout());

        txtPista.setColumns(20);
        txtPista.setRows(5);
        pnlPistas.add(txtPista, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlPistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 350, 350));

        btnGenerar.setForeground(new java.awt.Color(0, 102, 255));
        btnGenerar.setText("Empezar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 130, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("Nombre de Jugador");
        jLabel2.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 200, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pedroabarcaiiproyecto/images/depositphotos_4051311-Seamless-letters.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
      
        pnlCrucigrama.removeAll();
        pnlCrucigrama.setVisible(false);

        Cuadro[][] matriz = cuadroBO.getCrucigrama();
        
     //   System.out.println(matriz[0].length);//  borrar
        for (int i = 0; i < matriz.length; i++) {
            for (int j = 0; j < matriz[i].length; j++) {
                Cuadro c = matriz[i][j];
                JLabel label = new JLabel();
                label.setText(c.getPista() == 0 ? "" : String.valueOf(c.getPista()));
                label.setHorizontalAlignment(SwingConstants.CENTER);
                JTextField txt = new JTextField();
                txt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                txt.setHorizontalAlignment(JTextField.CENTER);
                txt.setText(c.getLetra());
                txt.setBorder(null);
                if (c.esNegro()) {
                    txt.setBackground(Color.BLACK);
                    txt.setOpaque(true);
                    txt.setFocusable(false);
                }
                pnlCrucigrama.add(label, new AbsoluteConstraints(x, y, 12, 12));
                pnlCrucigrama.add(txt, new AbsoluteConstraints(x, y, 33, 33));
                x += 30;
                txt.addKeyListener(new java.awt.event.KeyAdapter() {
                    @Override
                    public void keyTyped(java.awt.event.KeyEvent evt) {
                            if (txt.getText().length()== 1) {
                                evt.consume();
                            }     
                    }
                });
            }
            y += 30;
            x = 4;
        }
        pnlCrucigrama.setVisible(true);
        pnlCrucigrama.setBackground(Color.BLACK);
        pnlCrucigrama.setOpaque(true);
        pack();
    }//GEN-LAST:event_btnGenerarActionPerformed
    
                    
         
        
    
            
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel plnTablero;
    private javax.swing.JPanel pnlCrucigrama;
    private javax.swing.JPanel pnlPistas;
    private javax.swing.JTextArea txtPista;
    // End of variables declaration//GEN-END:variables
}
